bath:
  path: http://localhost:8988
dragon:
  flow:
    message-enabled: false
kisso:
  config:
    cache-expires: 7200
log:
  level: INFO
  path: d:\data\applogs\flow
scheduling:
  enabled: false
server:
  port: 8988
spring:
  datasource:
    url: jdbc:mysql://${DB_MYSQL_HOST}:3306/flow-6.7?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: ${DB_MYSQL_USER}
    password: ${DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
